<?
require_once("locallist.php");

class SourceList extends LocalList
{

	function LoadAll()
	{ /*$query = "
SELECT SOURCES.*,
(SELECT NAME FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE]='main_author' 
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'MAIN_AUTHOR',

(SELECT NAME FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE]!= 'main_author' 
AND AUTHORS_SOURCES_LINKS.[ROLE]!= 'author'
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'EDITOR',

(SELECT [ROLE] FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE] != 'main_author' 
AND AUTHORS_SOURCES_LINKS.[ROLE]!= 'author'
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'EDITOR_TYPE',

REVERSE(STUFF(REVERSE((SELECT NAME + ', ' [text()]
FROM AUTHORS, AUTHORS_SOURCES_LINKS  
WHERE (AUTHORS_SOURCES_LINKS.[ROLE]= 'main_author' 
OR AUTHORS_SOURCES_LINKS.[ROLE]= 'author')
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR 
for xml path(''))),1,2,'')) AS 'AUTHORS'
FROM SOURCES";*/
	
	$query = "SELECT *,
(SELECT TOP 1 NAME FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE]!= 'main_author' 
AND AUTHORS_SOURCES_LINKS.[ROLE]!= 'author'
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'EDITOR',

(SELECT TOP 1 [ROLE] FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE] != 'main_author' 
AND AUTHORS_SOURCES_LINKS.[ROLE]!= 'author'
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'EDITOR_TYPE',

(SELECT TOP 1 NAME FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE]='main_author' 
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'MAIN_AUTHOR',

dbo.ConcatNames(ID) AS 'AUTHORS' FROM SOURCES";
		
		$this->LoadFromSQL($query);
	}

	function LoadPage($start, $length, $order = 'id', $search)
	{
		if ($order == '') $order = 'id';
		if ($search != "") $search = "WHERE bibtex LIKE '%$search%'";
		$query = "SELECT BIBTEX, ID FROM (  
 SELECT BIBTEX, ID, ROW_NUMBER() OVER (ORDER BY $order) as row
 FROM SOURCES $search
 ) a WHERE a.row > $start and a.row <= $length ORDER BY $order ";

		$this->LoadFromSQL($query);
//		print_r($query);
		//var_dump($order);
	}
	function Count($search = "")
	{
		if ($search != "") $search = "WHERE bibtex LIKE '%$search%'";
		$query = "SELECT count(id) FROM SOURCES $search";
		$stmt = GetStatement();
		return $stmt->FetchField($query);
		//print_r($retVal);
	}
	
	function Load($source_id)
	{	

			$query = "SELECT TOP 1 *,
(SELECT NAME FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE]!= 'main_author' 
AND AUTHORS_SOURCES_LINKS.[ROLE]!= 'author'
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'EDITOR',

(SELECT TOP 1 [ROLE] FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE] != 'main_author' 
AND AUTHORS_SOURCES_LINKS.[ROLE]!= 'author'
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'EDITOR_TYPE',

(SELECT TOP 1 NAME FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE]='main_author' 
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'MAIN_AUTHOR',

dbo.ConcatNames(ID) AS 'AUTHORS' FROM SOURCES WHERE SOURCES.ID =".$source_id;
		
		$this->LoadFromSQL($query);
	}
	
	function GetAuthors($source_id)
	{	
			$query = "SELECT TOP 1 AUTHORS.*
  FROM AUTHORS, AUTHORS_SOURCES_LINKS WHERE 
  (AUTHORS_SOURCES_LINKS.[ROLE] ='author' OR AUTHORS_SOURCES_LINKS.[ROLE] ='main_author') 
  AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR 
  AND AUTHORS_SOURCES_LINKS.ID_SOURCE =".$source_id;
		
		$this->LoadFromSQL($query);
	}	
	
	function LoadSources($id)
	{
		$query = "SELECT *,
(SELECT NAME FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE]!= 'main_author' 
AND AUTHORS_SOURCES_LINKS.[ROLE]!= 'author'
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'EDITOR',

(SELECT TOP 1 [ROLE] FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE] != 'main_author' 
AND AUTHORS_SOURCES_LINKS.[ROLE]!= 'author'
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'EDITOR_TYPE',

(SELECT TOP 1 NAME FROM AUTHORS, AUTHORS_SOURCES_LINKS
WHERE AUTHORS_SOURCES_LINKS.[ROLE]='main_author' 
AND SOURCES.ID = AUTHORS_SOURCES_LINKS.ID_SOURCE 
AND AUTHORS.ID = AUTHORS_SOURCES_LINKS.ID_AUTHOR) AS 'MAIN_AUTHOR',

dbo.ConcatNames(ID) AS 'AUTHORS' FROM SOURCES, BIBLIOLINKS WHERE SOURCES.ID = BIBLIOLINKS.ID_SOURCE AND BIBLIOLINKS.ID_RECORD=".$id;
		
		$this->LoadFromSQL($query);
	}

}
?>